### ISSUE TITLE
Fallback Cache Key 

### ISSUE THREAD

**Issue by phil-lgr** [cypress-io/cypress-example-kitchensink#122]
https://github.com/cypress-io/cypress-example-kitchensink/blob/master/circle.yml#L16

there should be a fallback cache key, something like:
```yaml
- restore_cache:
    keys:
        - cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
        # fallback to using the latest cache if no exact match is found
        - cache-
```
