### ISSUE TITLE
Figure out caching on Azure CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#132]
When running on Azure CI public pipelines, I do not see any way to cache NPM dependencies or Cypress binary between the runs. This lead to 3-5 minutes of install time per run.

- need to cache `~/.npm` and `~/.cache` folders somehow

**Comment by bahmutov** [comment]
- resources at https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=vsts&tabs=new-nav do not show how to cache node modules

**Comment by bahmutov** [comment]
Sample project: https://github.com/MicrosoftDocs/pipelines-javascript but does not show any caching for `node_modules` or `~/.npm` folders

**Comment by bahmutov** [comment]
More details suggested by other MVPs
- https://stackoverflow.com/questions/44546183/correct-way-to-use-npm-cache-vs-team-services
- https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/32044321-improve-hosted-build-agent-performance-with-build

Seems Azure CI team is working on general caching solution, might make sense to wait for them

**Comment by brandonb927** [comment]
Azure DevOps Pipeline caching [came out of preview the other day](https://devblogs.microsoft.com/devops/improved-continuous-delivery-capabilities-and-caching-for-azure-pipelines/). It would be great to have an example of how to cache the Cypress binary in YAML Pipelines, as I am currently struggling to make it work.

**Comment by ekulabuhov** [comment]
Hi! It might be useful to add that on a windows based image the path is different and looks like this:
```
- task: CacheBeta@1
  inputs:
    key: 'cypress | $(Agent.OS) | package-lock.json'
    path: 'C:\Users\VssAdministrator\AppData\Local\Cypress'
    restoreKeys: 'cypress | $(Agent.OS) | package-lock.json'
  displayName: Cache cypress binary
```

Unfortunately, caching in Azure Pipelines is a bit crippled due to security restrictions described here: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#cache-isolation-and-security

Basically, caches are isolated between different branches which makes them less useful when used with feature branches.
