### ISSUE TITLE
Add GitHub Actions CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-kitchensink#286]
To show how to run Cypress e2e tests using the new GitHub Actions CI
- record to Dashboard
- run several containers in parallel

**Comment by kieranklaassen** [comment]
Would love to see GitHub actions CI implemented on the repo!

**Comment by bahmutov** [comment]
@amirrustam was working on it, seems actions are still missing proper NPM caching and also the environment variables for parallel runs are somewhat tricky

**Comment by amirrustam** [comment]
Working closely with GH team to on this that will potentially improve some of these beta-level wrinkles for everyone.

**Comment by HugoGresse** [comment]
I was smoothly able to record on dashboard with the new Github Actions 
see https://github.com/HugoGresse/open-feedback/blob/master/.github/workflows/test-e2e.yml
I have not tried the parallelization though.

**Comment by csi-lk** [comment]
Also have setup a really [simplistic version here](https://github.com/csi-lk/cypress-gwt-example/blob/master/.github/workflows/run-cypress.yml)

**Comment by mikecousins** [comment]
Any idea how to get an environment variable from Github Actions that we can use for --ci-build-id?

**Comment by HugoGresse** [comment]
@mikecousins you can setup env var from the Github repo settings ans use them like so: 
```
    - name: npm install, build
      run: |
        npm install
        npm run build --token ${{ secrets.REACT_APP_API_KEY }}
      env:
        CI: true
        REACT_APP_API_KEY: ${{ secrets.E2E_FIREBASE_API_KEY }}
```
