### ISSUE TITLE
Cypress hangs indefinitely on AWS Amplify

### ISSUE THREAD

**Issue by stevensacks** [cypress-io/cypress-example-kitchensink#327]
I'm not sure if this is an issue with Cypress or Amplify, but I went into detail here:
https://github.com/aws-amplify/amplify-console/issues/240

I followed the instructions exactly as stated in yours and Amplify's documentation and no matter what I do, it always hangs indefinitely after Cypress launches.

**Comment by stevensacks** [comment]
I've discovered some things, which I have noted in the above issue. 

1. Cypress does not work on Amplify if you use Yarn to build your Create React App. I had to switch to npm with package-lock.json to get it to work.
2. Amplify does not serve the development server from the URL that Cypress expects. But, even when I change the wait-on URL in the amplify.yml to match, Cypress still doesn't run and hangs indefinitely.

At this point, I don't know what's wrong, but considering I'm following your documentation to the letter, seems like it's something to be worked out with the Amplify team.

**Comment by stevensacks** [comment]
I'm updating both places. The Cypress docs explicitly say do not cache the node modules folder, yet your kitchen sink amplify.yml file does exactly that.

Your file:
https://github.com/cypress-io/cypress-example-kitchensink/blob/master/amplify.yml#L14-L16

Your docs:
https://docs.cypress.io/guides/guides/continuous-integration.html#Caching

> Do not cache node_modules across builds. This bypasses more intelligent caching packaged with npm or yarn, and can cause issues with Cypress not downloading the Cypress binary on npm install.

Which one is correct? Because I turned off the `--record` flag, and got this error in the amplify log.

```
2019-11-13T09:43:31.101Z [INFO]: # Executing command: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss
2019-11-13T09:43:31.377Z [INFO]: The cypress npm package is installed, but the Cypress binary is missing.
                                 We expected the binary to be installed here: /root/.cache/Cypress/3.6.1/Cypress/Cypress
                                 Reasons it may be missing:
                                 - You're caching 'node_modules' but are not caching this path: /root/.cache/Cypress
                                 - You ran 'npm install' at an earlier build step but did not persist: /root/.cache/Cypress
                                 Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.
                                 Alternatively, you can run 'cypress install' to download the binary again.
                                 https://on.cypress.io/not-installed-ci-error
                                 ----------
                                 Platform: linux (Raspbian - 2)
                                 Cypress Version: 3.6.1
```

**Comment by stevensacks** [comment]
As per the docs on Cypress, I removed node_modules from the cache, and changed it to this:

```yml
  cache:
    paths:
      - ~/.cache
```

I no longer get the above error from Cypress, but it hangs indefinitely again.

```bash
2019-11-13T10:01:12.737Z [INFO]: Starting the development server...
2019-11-13T10:01:27.893Z [INFO]: Compiled successfully!
2019-11-13T10:01:27.895Z [INFO]: You can now view frontend in the browser.
                                 Local:            http://localhost:3000/
                                 On Your Network:  http://172.17.0.2:3000/
                                 Note that the development build is not optimized.
                                 To create a production build, use yarn build.
2019-11-13T10:01:29.403Z [INFO]: # Completed phase: preTest
                                 # Starting phase: test
2019-11-13T10:01:29.405Z [INFO]: # Executing command: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss
```

**Comment by kevinold** [comment]
@stevensacks Thanks for this report. 

Will you please provide one of the following:

- A link to a repo that has the project/configuration with amplify.yml 
- the latest complete amplify.yml

I will review and work with the Amplify team if necessary to learn more about what may be going wrong.

**Comment by stevensacks** [comment]
It’s a private repo. There’s nothing too proprietary in there, but I’ll have to make a clean version to share it. In the meantime, here’s my amplify.yml.

```yml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run test && npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - ~/.cache
test:
    artifacts:
        baseDirectory: cypress
        configFilePath: "**/mochawesome.json"
        files:
            - "**/*.png"
            - "**/*.mp4"
    phases:
        preTest:
            commands:
                - npm install
                - npm install wait-on
                - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
                - "npm start & npx wait-on http://172.17.0.2:3000"
        test:
            commands:
                - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        postTest:
            commands:
                - npx mochawesome-merge --reportDir cypress/report/mochawesome-report > cypress/report/mochawesome.json
```
