### ISSUE TITLE
Parallelization in AWS codebuild

### ISSUE THREAD

**Issue by sridhar562345** [cypress-io/cypress-example-kitchensink#555]
```yaml
version: 0.2
batch:
   fast-fail: true
   build-matrix:
      static:
         ignore-failure: false
         env:
            privileged-mode: true
      dynamic:
         env:
            variables:
               WORKERS:
                  - 1
                  - 2
                  - 3
phases:
   pre_build:
      commands:
         - npm install cypress --save-dev
         - yarn run cy:verify
         - yarn run cy:info
         - sysctl fs.inotify.max_user_watches

   build:
      commands:
         - yarn install
         - REACT_APP_SSO_ENABLED=false yarn start & npx wait-on http://localhost:3000
         - yarn run:cypress-parallel-tests
 ```

The `yarn install` command running in each codebuild batch and taking a long time, how can i modify the buildspec to only run this only once and not in all parallel builds?
